[theme]
base = "light"
primaryColor = "#0B7A75"
backgroundColor = "#F3F5F7"
secondaryBackgroundColor = "#E6EBEF"
textColor = "#14202B"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
